Hw3 my tree set
NeKp0T/javaHomework pull request #3
Opened 2019-02-04 18:40 UTC by NeKp0T

2019-02-09 20:21 UTC, yurii-litvinov requested changes

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +public class MyTreeSetBinary<E extends Comparable<? super E>>
Не-а, E не обязан быть Comparable. Если нам передали компаратор, натуральный порядок всё равно не используется, так что и требовать его нельзя.

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +    class TreeIterator implements Iterator<E> {
Лучше private, даже с учётом того, что у него есть дополнительный метод previous. От этой структуры данных не ожидается возможность обхода в разных направлениях, а показывать наружу конкретный тип итератора --- не по делу нарушать инкапсуляцию. И в любом случае, тогда уж его лучше сделать public.

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +            return new DescendingIterator();
И при этом DescendingIterator не является TreeIterator, так что `(TreeIterator)tree.iterator();` отработает нормально и даст нам возможность вызывать previous(), а `(TreeIterator)tree.descendingIterator();` внезапно упадёт. В общем, предлагается сделать TreeIterator private.

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +    public boolean add(E e) {
`@Override`? Да и `/** {@inheritDoc} */` бы не помешал

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +        int dir = comparator.compare(node.value, e);
dir --- directory? :)

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +        @SuppressWarnings("unchecked") E element = (E) o;
Не, если компаратор не против, он может принять объект и другого типа, почему нет. Кастать тут преждевремено.

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/test/java/MyTreeSetBinaryTest.java
> +import com.example.treeSet.MyTreeSet;
Юнит-тесты тоже неплохо бы в пакете

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/test/java/MyTreeSetBinaryTest.java
> +    private void putbcabToSet(MyTreeSet<String> set) {
Тогда уж `putBcabToSet`, camelCase же

2019-02-09 20:21 UTC, yurii-litvinov commented on MyTreeSet/src/test/java/MyTreeSetBinaryTest.java
> +    }
Хитро, но для этого придумали параметризованные тесты (https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-parameterized-tests/). Правда, про это ещё не было, так что можно пока и так :)

2019-02-10 12:31 UTC, NeKp0T commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +        @SuppressWarnings("unchecked") E element = (E) o;
TreeMap.getEntryUsingComparator делает так же.
А компаратор все равно принимает только E, так что я не понимаю, в чем выгода.

2019-02-10 18:25 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +        @SuppressWarnings("unchecked") E element = (E) o;
Он же ? super E, он принимает любого предка E, например, Object.

2019-02-10 18:44 UTC, yurii-litvinov requested changes

2019-02-10 18:44 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +    public <T extends Comparable<? super T>>
Подозреваю, что это ни на что не влияет, потому что параметр T нигде не используется и компилятору не понять, что это ограничение на тип E.

2019-02-10 18:44 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +    public boolean add(E e) {
Здесь сделали, а ниже нет. inheritDoc ладно, от него всё равно польза сомнительна, а вот `@Override` грешно не писать. В C# без override бы вообще не скомпилилось.

2019-02-10 21:01 UTC, NeKp0T commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +        @SuppressWarnings("unchecked") E element = (E) o;
.compare(..., o) не копилится
Вроде ? super E должен принимать все что кастится к любому X, что Object <: X <: E, то есть только потомков E

2019-02-11 19:37 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +        @SuppressWarnings("unchecked") E element = (E) o;
Не, тут всё хитрее. `? super E` означает "Любой предок E", но это тип компаратора. Так что объявление `private final Comparator<? super E> comparator;` разрешает компаратору быть любого типа от `Comparator<E>` до `Comparator<Object>`, так что мы можем передать в конструктор нашему множеству любой такой компаратор. Что логично: если компаратор принимает Object, он может как-нибудь справиться и с E. Но, тут мы пытаемся сделать `comparator.compare(findAdjacent(o).value, o)`, что, во-первых, вызывает огорчение у findAjacent, который хочет E (но это понятно), во-вторых, компаратора, который огорчён, что o это Object. Вот это уже интереснее. Но на самом деле понятно, что от нас хотят --- компаратор может быть любым от `Comparator<E>` до `Comparator<Object>`, так что этот вызов может быть безопасным действительно только для значений типа E или его потомков --- потому что а вдруг компаратор именно `Comparator<E>` и ничего более общего сраввнивать не умеет. Но тогда в чём профит от ограничения типа `<? super E>`? На самом деле в том, что реальный тип компаратора можно из него достать, он же известен во время компиляции для каждого экземпляра шаблона: https://docs.oracle.com/javase/tutorial/java/generics/capture.html

Так что вот так скомпилится:
```java
    @Override
    public boolean contains(Object o) {
        if (isEmpty()) {
            throw new NoSuchElementException();
        }
        // Will throw ClassCastError if o's type isn't successor of E
        // not empty => findAdjacent returns not null
        return compare(comparator, o);
    }

    private <T> boolean compare(Comparator<T> comparator, Object o) {
        return comparator.compare((T)findAdjacent((E)o).value, (T)o) == 0;
    }
```
Хотя это, конечно, не очень, потому что в Java почему-то нельзя записать lower bound-ограничение на параметр-тип генерик-метода. Компилятор, естественно, предупредит о непроверяемом касте от E к T (хотя по логике вещей T всегда предок E).

В общем, действительно получилось несколько сложнее, чем я рассчитывал, так что можно не править. Но на всякий случай вот годная статья, где объясняется всё, что происходит с extends и super в wildcard-ах: http://tomasp.net/blog/variance-explained.aspx/. Там, правда, примеры на C#, но тут главное не язык, а стоящая за этим теория.

2019-02-11 19:40 UTC, yurii-litvinov approved these changes

2019-02-11 19:40 UTC, yurii-litvinov commented on MyTreeSet/src/main/java/com/example/treeSet/MyTreeSetBinary.java
> +     * {@inheritDoc}
Мм, мне кажется, для конструкторов оно не работает, потому что виртуальных конструкторов не бывает

2019-02-12 14:10 UTC, merged