Hw4 phonebook
NeKp0T/javaHomework pull request #5
Opened 2019-02-19 20:31 UTC by NeKp0T

2019-03-06 07:47 UTC, yurii-litvinov requested changes

2019-03-06 07:47 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +final class Entry {
Лучше каждый класс в своём файле, даже мелочь всякую. Файлов-то не жалко.

2019-03-06 07:47 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +                + " id integer PRIMARY KEY,\n"
Таблице-развязке свой первичный ключ, в общем-то, не нужен --- на неё-то никто ссылаться не собирается (я надеюсь). Удалять из неё проще по суррогатному ключу --- паре внешних ключей, ссылающихся на имена и телефоны.

2019-03-06 07:47 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +    public ArrayList<Entry> findByName(String name) throws SQLException {
Надо комментарии

2019-03-06 07:47 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +        return selectByQuery(query, "crutch"); // eeh its better than creating another method
:)

2019-03-06 07:47 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +    }
Я бы на самом деле после всех удалений из талицы-развязки ещё подчищал имена и телефоны, на которые никто не ссылается

2019-03-06 07:47 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +    }
Этот метод поверг Codacy в ужас. И если switch по командам ещё ладно (можно вынести исполнение каждой команды в метод, но это, скорее всего, доставит больше боли, чем радости), то разбор state.type можно было делать отдельно.

2019-03-06 07:47 UTC, yurii-litvinov commented on Phonebook/src/test/java/com/example/phonebook/PhonebookDatabaseControllerTest.java
> +    PhonebookDatabaseController db;
Оо, пакетное поле, прямиком из таблицы роковых ошибок

2019-03-08 10:56 UTC, NeKp0T commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +                + " id integer PRIMARY KEY,\n"
Там есть команда "удалить запись по ее id" так что оно используется

2019-03-10 10:42 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +                + " id integer PRIMARY KEY,\n"
Да, это я видел, но не то чтобы мне это нравится. Тут составной ключ более уместен.

2019-03-10 10:49 UTC, yurii-litvinov approved these changes
Стало лучше, серьёзных замечаний не осталось, зачтена

2019-03-10 10:49 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Entry.java
> +// tuple of name, phone and id.
Но почему оно не JavaDoc? :)

2019-03-10 10:49 UTC, yurii-litvinov commented on Phonebook/src/main/java/com/example/phonebook/Main.java
> +    private static class ConnectState {
Я б и эти классы вынес в отдельный файл и сделал пакетными, для уменьшения объёма кода в одном файле. Так читать удобнее

2019-04-03 21:13 UTC, merged